### ISSUE TITLE
[nuget]: Create NuGet package for WebUI4CSharp

### ISSUE THREAD

**Issue by xxyuze** [salvadordf/WebUI4CSharp#3]
Would you consider adding WebUI4CSharp to the NuGet or GitHub Package repository? This would improve accessibility, allow for better analytics.
For NuGet, you can create a package using a .nuspec file. More details are available [here](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package).

**Comment by salvadordf** [comment]
The Nuget packages are now available here : 
https://www.nuget.org/packages/WebUI4CSharp/2.5.0-beta.2
https://www.nuget.org/packages/WebUI4CSharp.Natives/2.5.0-beta.2
